config/routes.rb
Rails.application.routes.draw do
  resources :rels
  resources :rel_types
  resources :subjects
  resources :sub_types

  root "subjects#index"

  get '/subjects/set_tree/:id',
    to: 'subjects#set_tree',
    as: 'subjects_set_tree'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/rel.rb
class Rel < ApplicationRecord
  belongs_to :rel_type
  belongs_to :node1, class_name: 'Subject'
  belongs_to :node2, class_name: 'Subject'
end

app/models/rel_type.rb
class RelType < ApplicationRecord
end

app/controllers/rels_controller.rb
class RelsController < ApplicationController
  before_action :set_rel, only: [:show, :edit, :update, :destroy]

  # GET /rels
  # GET /rels.json
  def index
    @rels = Rel.all
  end

  # GET /rels/1
  # GET /rels/1.json
  def show
  end

  # GET /rels/new
  def new
    @rel = Rel.new
  end

  # GET /rels/1/edit
  def edit
  end

  # POST /rels
  # POST /rels.json
  def create
    @rel = Rel.new(rel_params)

    respond_to do |format|
      if @rel.save
        format.html { redirect_to @rel, notice: 'Rel was successfully created.' }
        format.json { render :show, status: :created, location: @rel }
      else
        format.html { render :new }
        format.json { render json: @rel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rels/1
  # PATCH/PUT /rels/1.json
  def update
    respond_to do |format|
      if @rel.update(rel_params)
        format.html { redirect_to @rel, notice: 'Rel was successfully updated.' }
        format.json { render :show, status: :ok, location: @rel }
      else
        format.html { render :edit }
        format.json { render json: @rel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rels/1
  # DELETE /rels/1.json
  def destroy
    @rel.destroy
    respond_to do |format|
      format.html { redirect_to rels_url, notice: 'Rel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rel
      @rel = Rel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rel_params
      params.require(:rel).permit(:rel_type_id, :node1_id, :node2_id)
    end
end

app/helpers/rels_helper.rb
module RelsHelper
end

app/views/rels/_form.html.erb
<%= form_for(rel) do |f| %>
  <% if rel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rel.errors.count, "error") %> prohibited this rel from being saved:</h2>

      <ul>
      <% rel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :node1_id, 'От элемента:' %>
    <%= f.collection_select :node1_id, Subject.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :rel_type_id, 'Тип связи:' %>
    <%= f.collection_select :rel_type_id, RelType.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :node2_id, 'К элементу:' %>
    <%= f.collection_select :node2_id, Subject.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rels/edit.html.erb
<h1>Editing Rel</h1>

<%= render 'form', rel: @rel %>

<%= link_to 'Show', @rel %> |
<%= link_to 'Back', rels_path %>

app/views/rels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Связи</h1>

<table>
  <thead>
    <tr>
      <th>От элемента</th>
      <th>Тип связи</th>
      <th>К элементу</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rels.each do |rel| %>
      <tr>
        <td><%= rel.node1.name %></td>
        <td><%= rel.rel_type.name %></td>
        <td><%= rel.node2.name %></td>
        <td><%= link_to 'Show', rel %></td>
        <td><%= link_to 'Edit', edit_rel_path(rel) %></td>
        <td><%= link_to 'Destroy', rel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rel', new_rel_path %>

app/views/rels/new.html.erb
<h1>New Rel</h1>

<%= render 'form', rel: @rel %>

<%= link_to 'Back', rels_path %>

app/views/rels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>От элемента:</strong>
  <%= @rel.node1.name %>
</p>

<p>
  <strong>Тип связи:</strong>
  <%= @rel.rel_type.name %>
</p>

<p>
  <strong>К элементу:</strong>
  <%= @rel.node2.name %>
</p>

<%= link_to 'Edit', edit_rel_path(@rel) %> |
<%= link_to 'Back', rels_path %>