config/routes.rb
Rails.application.routes.draw do
  resources :rels
  resources :rel_types
  resources :subjects
  resources :sub_types

  root "subjects#index"

  get '/subjects/set_tree/:id',
    to: 'subjects#set_tree',
    as: 'subjects_set_tree'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/controllers/rel_types_controller.rb
class RelTypesController < ApplicationController
  before_action :set_rel_type, only: [:show, :edit, :update, :destroy]

  # GET /rel_types
  # GET /rel_types.json
  def index
    @rel_types = RelType.all
  end

  # GET /rel_types/1
  # GET /rel_types/1.json
  def show
  end

  # GET /rel_types/new
  def new
    @rel_type = RelType.new
  end

  # GET /rel_types/1/edit
  def edit
  end

  # POST /rel_types
  # POST /rel_types.json
  def create
    @rel_type = RelType.new(rel_type_params)

    respond_to do |format|
      if @rel_type.save
        format.html { redirect_to @rel_type, notice: 'Rel type was successfully created.' }
        format.json { render :show, status: :created, location: @rel_type }
      else
        format.html { render :new }
        format.json { render json: @rel_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rel_types/1
  # PATCH/PUT /rel_types/1.json
  def update
    respond_to do |format|
      if @rel_type.update(rel_type_params)
        format.html { redirect_to @rel_type, notice: 'Rel type was successfully updated.' }
        format.json { render :show, status: :ok, location: @rel_type }
      else
        format.html { render :edit }
        format.json { render json: @rel_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rel_types/1
  # DELETE /rel_types/1.json
  def destroy
    @rel_type.destroy
    respond_to do |format|
      format.html { redirect_to rel_types_url, notice: 'Rel type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rel_type
      @rel_type = RelType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rel_type_params
      params.require(:rel_type).permit(:name)
    end
end

app/helpers/rel_types_helper.rb
module RelTypesHelper
end

app/views/rel_types/_form.html.erb
<%= form_for(rel_type) do |f| %>
  <% if rel_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rel_type.errors.count, "error") %> prohibited this rel_type from being saved:</h2>

      <ul>
      <% rel_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rel_types/edit.html.erb
<h1>Editing Rel Type</h1>

<%= render 'form', rel_type: @rel_type %>

<%= link_to 'Show', @rel_type %> |
<%= link_to 'Back', rel_types_path %>

app/views/rel_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rel Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rel_types.each do |rel_type| %>
      <tr>
        <td><%= rel_type.name %></td>
        <td><%= link_to 'Show', rel_type %></td>
        <td><%= link_to 'Edit', edit_rel_type_path(rel_type) %></td>
        <td><%= link_to 'Destroy', rel_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rel Type', new_rel_type_path %>

app/views/rel_types/new.html.erb
<h1>New Rel Type</h1>

<%= render 'form', rel_type: @rel_type %>

<%= link_to 'Back', rel_types_path %>

app/views/rel_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rel_type.name %>
</p>

<%= link_to 'Edit', edit_rel_type_path(@rel_type) %> |
<%= link_to 'Back', rel_types_path %>