config/routes.rb
Rails.application.routes.draw do
  resources :rels
  resources :rel_types
  resources :subjects
  resources :sub_types

  root "subjects#index"

  get '/subjects/set_tree/:id',
    to: 'subjects#set_tree',
    as: 'subjects_set_tree'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :sub_type
  has_many :inputs,  -> {order('rel_type_id').includes(:rel_type, :node1)}, class_name: 'Rel', foreign_key: :node2_id
  has_many :outputs, -> {order('rel_type_id').includes(:rel_type, :node2)}, class_name: 'Rel', foreign_key: :node1_id 
  has_many :to, class_name: 'Subject', through: :outputs, source: :node2 
  has_many :from, class_name: 'Subject', through: :inputs, source: :node1

  has_many :rels_out, -> {group(:rel_type)}, class_name: 'Rel', foreign_key: :node1_id 
  has_many :rels_in,  -> {group(:rel_type)}, class_name: 'Rel', foreign_key: :node2_id 


  def each_relation _side, level=0, cache={}, &block
    side = case _side
           when :in;  inputs
           when :out; outputs
           end
    p side.count, level  
    return if side.count == 0
    
    yield state: :new_level, level: level, node: self
    
    count_rels = rels_out.count
    last_section = nil
    new_level = true
    
    side.find_each do |rel|
      break if cache.has_key? rel
      cache[rel] = nil
      p !last_section.nil? 
      p last_section != rel.rel_type
      p "**************************" if !last_section.nil? #and last_section != rel.rel_type
 
      yield state: :end_rel, rel: last_section, count: count_rels[last_section], level: level if !last_section.nil? and last_section != rel.rel_type
      yield state: :new_rel, rel: rel.rel_type, count: count_rels[rel.rel_type], level: level if (last_section!=rel.rel_type)
      yield state: :start_node, node: rel.node2, level: level
      last_section = rel.rel_type
      rel.node2.each_relation _side, level+1, cache, &block
      yield state: :end_node, node: rel.node2, level: level
      new_level = false
    end
    yield state: :end_rel, rel: last_section, count: count_rels[last_section], level: level if !last_section.nil?
    yield state: :end_level, level: level, node: self
  end

  def change_name
    puts name
    puts name?
    puts self.name
    name = "new name"
    puts name.changed?
    self.name = "new name"
    puts self.name.changed?
    save!
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_action :set_hierarhy, only: [:index]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  # def build_tree id, subjects=[], exists={}, tree={}
  #   root = Subject.find(id)
  #     unless exists.has_key? root.id
  #       exists[root.id] = root.id
  #
  #       tree[root] = []
  #       root.outputs.each do |rel|
  #         tree[root] << {rel: subject.rel_type.name, }
  #       end
  #     end
  # end


  def set_tree
    @root = Subject.find(params[:id])
    # @tree = @root.get_children
    @subjects = nil # Subject.all.order(:name)
    #p @tree
    render :index
    # redirect_to subjects_path 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :sub_type_id)
    end

    def set_hierarhy
      @tree ||= {}

    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(subject) do |f| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Наименование элемента' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :sub_type_id, "Тип элемента" %>
    <%= f.collection_select :sub_type_id, SubType.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Элементы</h1>
<div><%= @tree %></div>

<% unless @subjects.nil? %>
<table>
  <thead>
    <tr>
      <th>Элемент</th>
      <th>Тип элемента</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.sub_type.name %></td>
        <td><%= link_to 'Root', subjects_set_tree_path(subject) %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <b><%= @root.name %></b>
  
  <% @root.each_relation(:out) do |response| %>
    <% case response[:state] %>
    <% when :new_level %>
      <div style="padding-left: 20px">
    <% when :end_level %>
      </div>
    <% when :new_rel %>
      <b><%= response[:rel].name %></b>
      <div class="relation" style="padding-left: 20px; border-left: 1px solid red">
    <% when :end_rel %>
      </div>
    <% when :start_node %>
      <div class="node"><%= response[:node].name %></div>
    <% when :end_node %>
    <% end %>
  <% end %>
<% end %>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Sub type:</strong>
  <%= @subject.sub_type.name %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>