config/routes.rb
Rails.application.routes.draw do
  resources :rels
  resources :rel_types
  resources :subjects
  resources :sub_types

  root "subjects#index"

  get '/subjects/set_tree/:id',
    to: 'subjects#set_tree',
    as: 'subjects_set_tree'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/controllers/sub_types_controller.rb
class SubTypesController < ApplicationController
  before_action :set_sub_type, only: [:show, :edit, :update, :destroy]

  # GET /sub_types
  # GET /sub_types.json
  def index
    @sub_types = SubType.all
  end

  # GET /sub_types/1
  # GET /sub_types/1.json
  def show
  end

  # GET /sub_types/new
  def new
    @sub_type = SubType.new
  end

  # GET /sub_types/1/edit
  def edit
  end

  # POST /sub_types
  # POST /sub_types.json
  def create
    @sub_type = SubType.new(sub_type_params)

    respond_to do |format|
      if @sub_type.save
        format.html { redirect_to @sub_type, notice: 'Sub type was successfully created.' }
        format.json { render :show, status: :created, location: @sub_type }
      else
        format.html { render :new }
        format.json { render json: @sub_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_types/1
  # PATCH/PUT /sub_types/1.json
  def update
    respond_to do |format|
      if @sub_type.update(sub_type_params)
        format.html { redirect_to @sub_type, notice: 'Sub type was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_type }
      else
        format.html { render :edit }
        format.json { render json: @sub_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_types/1
  # DELETE /sub_types/1.json
  def destroy
    @sub_type.destroy
    respond_to do |format|
      format.html { redirect_to sub_types_url, notice: 'Sub type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_type
      @sub_type = SubType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_type_params
      params.require(:sub_type).permit(:name)
    end
end

app/helpers/sub_types_helper.rb
module SubTypesHelper
end

app/views/sub_types/_form.html.erb
<%= form_for(sub_type) do |f| %>
  <% if sub_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_type.errors.count, "error") %> prohibited this sub_type from being saved:</h2>

      <ul>
      <% sub_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_types/edit.html.erb
<h1>Editing Sub Type</h1>

<%= render 'form', sub_type: @sub_type %>

<%= link_to 'Show', @sub_type %> |
<%= link_to 'Back', sub_types_path %>

app/views/sub_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_types.each do |sub_type| %>
      <tr>
        <td><%= sub_type.name %></td>
        <td><%= link_to 'Show', sub_type %></td>
        <td><%= link_to 'Edit', edit_sub_type_path(sub_type) %></td>
        <td><%= link_to 'Destroy', sub_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Type', new_sub_type_path %>

app/views/sub_types/new.html.erb
<h1>New Sub Type</h1>

<%= render 'form', sub_type: @sub_type %>

<%= link_to 'Back', sub_types_path %>

app/views/sub_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sub_type.name %>
</p>

<%= link_to 'Edit', edit_sub_type_path(@sub_type) %> |
<%= link_to 'Back', sub_types_path %>